### ISSUE TITLE
KDE Plasma support?

### ISSUE THREAD

**Issue by Warmuser** [erikdubois/Ultimate-Linux-Mint-18-Cinnamon#1]
Hello Erik, I really appreciate your work on Youtube and the projects that you have created. I want to ask you If you are planning to made a porting or extend the compatibility of these project also for KDE Plasma. Let me know, bye. :)

PS: I'm sorry. I confused the tabs. The request was for Surfn https://github.com/erikdubois/Surfn

**Comment by erikdubois** [comment]
should already be well supported... but not my favorite desktop environment - comes last on the to-do list

**Comment by Warmuser** [comment]
Ok, thanks! :)
