### ISSUE TITLE
Missing space for level 2 titles in README.md

### ISSUE THREAD

**Issue by mat-m** [erikdubois/Ultimate-Linux-Mint-18-Cinnamon#2]
You miss a space between the ## and the text.

**Comment by mat-m** [comment]
@erikdubois I can submit a PR if you prefer. Your repo is useful, I'm just trying to help :)

**Comment by erikdubois** [comment]
please do
i have no time to keep maintaining my personal githubs
But I have no issue you maintaining my code on your github either
and me writing to go get the code on your github
